apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: artifactory-access
  namespace: ci
spec:
  encryptedData:
    ARTIFACTORY_ENCRYPT: AgCFjDaTUEZ/K53ZhB1i61Tw/jzXcvscSFdh1mBdt8YXQX4ohBTaBhCO6KPYlP3eSZoFm61EEPg/5qPUc7iHGvROutXmI7ikDhM3oiA9lJp9PS5Io99V57MPqmyMJO8cjgpoySJ2Jx4VEQzs7EAlM9Mav5YhxrfRDnfy1ToNAcKv2U4tnAzrHurR4GeGNZVhD7zeXluhASZYxXqNgTmuG2eX9XrPrZGK/247g8BP2arw8bZ0tpPDov1HCrHW0uaFxnouGVURR7k1jzax4tvuVU2ebcX37ovInRFoVDHCOgu6K1mdw6D72rD2qIYwOBCsau1hEkRlfka72npIzBMflHSfOUWF/dQBtnCtUvoQ0gkqxRYzDyzF2Do6qA7rO1aw1pAD0OtM2sbuChvsNtldm8RoHeeJVy93pY3Ne2nvq/6O8ii0PVt0iwpzYWZPe4/u+4hlzoALCq5/hJ98IzrjjNOLE7yh0x6cs4+slEw8vpXxmmHSvqH222uOxN57Z4gG/9ucRlEGyHuwKnO3FdjJgA5rwJPWa0atKx8phfmEVePxwuk/a8Ikv8UpGBuwT3ART7fnL/TKIwK0fPKmiAlreBa0OY8Bl+BkyfWCTcS8YAf0tEPscmk7YLv9NZ/3ADz8tswjmCq0cvVH8EFMMciR/mpGXNGOZ0pY22zveSv5E418KvDAy1NSWJAeRfWJc397W2YCOLftCaNRZD5cNuLUv/jR1DbHJO8GpFTqZM2j3PYt2LI7jKMhdA==
    ARTIFACTORY_PASSWORD: AgCLhQ489yLBvXoiim5d2ZIrRsfJ8Z42yVA/PRm59w5ol9pCA6vyomuFh0oxitS9u9aZoj0E/ECu+iUABRekd/h8zeUYmZk26wPE7B5biv8huXhqbSvInsnFhsiCRrGhSk0tkzZDz2q4V3dXQzxTCJX+7atJzcdHLRWLPcgluprESmvrBKiBWgl8PPivZ4PbG9+IJMfqnmgRid+uH3VG+PjhpIV58zv8/WvIiwcISZUfHGqCHG2HBKhYhTxm8n9dhnB3ryIpDjZN8oQ/EJyHTFRrXHrHoWKG3AZlaiQs6nTWTYoGyrNqgWbcg6AwumyO/ZvYrRsYEM1YbKjF/vRvP55+gwUeaFQQPI8tXgfHu1BdrKeTyE501zH+3emzB6S83vu4BpTQauY0zDbQYhEzAXOXtVpp6zaPt+epcOhFwfYqetLTWEmA48MjNY/RLN6IqiX6rdp3nRZm4Zgloi28oUlDuFvUOWRd6rBxb9dQOFsRgHVdRAUxCWwWBn80RGvb3ZLOCODnl8viIh4JnAxGxOiaujC58l8wK2CESCKofbm5GDqMz76ptMQuNAnO6FAR+wuPkJ0OUhNvTNSXO8jnn7Vh1f7ke0fVmTNCCMxx2PP53GHqkX09byDP3d9BgMTVIA3P3KgRsEMGNWMLipeGRT3Gj0kXQmDg36JEXVWurQ+XWCVRMhqqICVj1wXIo3AUJt1L1rkJSJoTEHiHuKGL02WUFnMYVQ==
    ARTIFACTORY_URL: AgBGVM5/crPfZitqV3a0VOSRFC73TdGIPxyw+au/pAqt8qz+NH+6fE1Hv2TfmvxogibC/R0iRe/VOB8ANsmhcJHs5zJu5Qkc1zE0sRPZ1IEl9r2LNC414bxLE4tYDJcKTL6PCKSUk4PNSPUWDBWDamdjNCQ5vy4LKQwGyR82Y4H9cZ9BODWLP2IoN6ncfzXcrtTd2/ZCqsWKA2UtpSr85VwwHlApcpNxGh4kr3Tsj7kqqkExZV2edSp+COrr9bVRbwP8534NqKuMbQpCRff5MsypeURsgl+Zn4KPhRzrJEMVC+NAkStV8boGD2t0wldr3D/ERgiIiIuHhgFQykyq5Mxdvmx4E/GKdH1KRYosoi5ps5sODB4rrF1A9+ozzWiKOJKrCbMlObyAOZkAkkd/WDESBbb6XJ8uPDFFSQQrjxYSaj+Mgp43jXRUMkng+UdAKTprzlm3m+CI9+U8dB2A3+6z8MEmUo4GaOOMm8WNO2R3cfwbXOvJN+hPRu4tduxynrpVM/H+CkQqvfZo+uckdxX57ZuWqIzaq2BFO2QPzySB1PT99ZG751gYnnPf/VmrCfz4sprxeDZC/+o1QiYIuly8+WyEyhw9a7j2DqCo/pJ1BO2D7HX8vrqoPNjPL1SAMdS7ZCJimHeybgPGyatkGQuCy6xq0fRdlSdjeq/BHVklW0pghU6Ey/fBeCbziCsrcusdP7p6FX/cX/192KEJ+drZolbs4PaEAU5ALxqNtZF6yybhvxH/6mLWOQ==
    ARTIFACTORY_USER: AgB9yys7+7zphuO4D71X+EO+BrurwuvNjbdIoUVdfk3dfhvxjcs7qhFc7r12Z9P4PPXkEsO5nGGsiqujrO+J3d3rpE+M4BtEzPuwaCN+r/DHtkPRiqjeHMhK+LuPDoerogjDeXG0w8xN6Y1WPdcW/DjWT+QJWXWhOIhR9qPBKP/YVQb/Ru+fUOtaocBrYKejOFsY/t4H1nEnVpVXCkIN4KHjwqVo597ZnD08dviZTIOD64RC3uPmwuoa4h2DSt50XBjsFNEr9B3+/7RnZYg6PfXFUDGlSOA1Vt1W3KqmQOsG41n1eAnQQDtfQP+NTJgMF7qnVZgU/QZ1PR2UM0ZRAmJLS6L9eipuYKEQLevLtgZ4FHmY3fJP6imOJskG0vXCzv+KRBZ5DYA9H0Q3s/zt4nHwu2uKdOMbIMzeyCtn35Z2Q6bcBX/G1VPG84setJuTKJKdjXzpdFLUjgwEsNFjt/J0vv3B00xk7/kdkQKdeyx01pH+8pdYcm0t0C9vHpGtv8LVsXV3qbjiPXO4OO0UvMInpAjnhprk5XkZX2oZCcWIBypNkTkDLkB7gt8roNteGm0Iq27ocdmrrWvA8Ozm8hZKwWvftVFNWpnb8mUaY7rnRqkxIyIZDKKvz/3gjW6M13ISsZzLpV3v6DBVBZ5HAOl0fRwsMqVOaeAgY7F38yLpjOkFBDz2JmexpvfXZJYGes4UVDbb+Q==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:ARTIFACTORY_URL: {}
            f:ARTIFACTORY_USER: {}
          f:type: {}
        manager: kubectl
        operation: Update
        time: "2021-09-17T05:48:34Z"
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            f:ARTIFACTORY_ENCRYPT: {}
            f:ARTIFACTORY_PASSWORD: {}
        manager: unknown
        operation: Update
        time: "2021-09-17T05:49:50Z"
      name: artifactory-access
      namespace: ci
    type: Opaque

