apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: git-credentials
spec:
  encryptedData:
    password: AgAsJJPbpjL5zLiPrp7kxkN9nAQE3jSVvF0nmBVfMPFaqehDqABitbL3+AeGEqYVeiDKw8R9kdReMjd8c9G5j2PPxf3HzU9VFkcGzlMkEvr7FEGcPQpW4xV16nQCV9lkUgaKXsuVGLvqtSnjiSjUlBK0GcA+38v1n3Sf7roeko0VLvMpfV2N+q603lOnFUWXH/znUCKl2CXwkZVBlBWzk+pZKno4lbofsDabJJayGQbqENC8nHx1Ps1Tly1XFC0YsDEnylZ0X1ZxK2OdPacnCkMtFsKElMVEe07Yctc8MpCv08vjUq/MFJHIjIvjukoXeiwKAogY8D8hmiaXyfnGG5eF84svoJLRIJ7xpW0pIlxQ6VBa0jvKYGyU1JI1gAFdSeuvbSVZvmKDe6K1AlDuuFG2nykbdS8da69paFEKNTADuH41An4UAqhaDVH1WAZeYQw/wVadIrxiXnAwW0C4LXAMG+NDB1xSU8qmRS2Rz/dbb6en+ANhao4EcjOGl6qfiLEgDz3teHCpskfsKV64iJrpYU/lal1nq0ygny8TZAKtIPgL2xFaPCDrd/OvySJRIp8bvUS9nOAmb1iQnc/Zs8eyJv/p5SWVUEN6aMNuLoTJ88KsG4UgZ3Nf6FMROCvvkN0gTgtx8GFUfzF1yuHRf9IiyY+ZQAKI1lwAyQIGKKhKRKckqSH62dEYj+qGh0d4n8DVcF/XJYX+BkE6el3LVkN3N1mdDFbslnkNt0jNoRiyg+l9XKNBUcCn
    username: AgA5KX0CpThkVSxJkDmn52wcrjPSGIFRRFgXG6ssZlAZ86iDT6cFucbIj1sweez/J0eqT4ldtDOucTL5A85ak5vQda1wHFPdDlEcL6i/fYIrqX5DPyZ7hxrjHnUBUIKMEXmBC+4WwYYuFBe/CQ9g9ASnKW0KOvD9NEgniSQKwS9SEarXK2sefeigtWxepG5pZL6wNee6HDQ/CEZmLjvYfHsZ3NpLR8jKrK++1b4QA8KcTLzB9QFFYqOqrBBqmOkHQoojl83v6zKsyX1sYR0WR8mNp3kVOA9zKf68KlnsE7Yd8L5p1bQJ6nOCdCaQJptqlJy81Aqoqc3f7a2RKPXQTM5qCvllk76bwiruXt79cAAA+GC1zQlAYCu4eRJeVgy+XYzYuzz0YFm8s62xZ1z89S76/W1a3DYEW7LLqs0+3ps//PIDiMxhyTymiOun/RZoC+ylwCtUdeNMfhwpBZqATai/nsoP5YeJoNl6DcDbgm6aEiFL1ze/+SSbXITmAz1Sp4pX7r/2m9pONUHD7/SgoDKYm+5tguKDvB7kEQ3JfnhTsSjY6duhIsu+cN+Vh8SBpd8UeaN47e9Lp1OD3e7gcgKvSnIcbqTzmYvZnD4zEGv2KoVTyJlMh1flYXGTv7NUZuDQCNdOrRjfT3bWW9wuT7mWulFZnJOUJT7XFLZIV1GS3H2vecV9demBxqlvo3eEbs207gmq3XgChw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
    type: kubernetes.io/basic-auth

